### GET all users
GET http://localhost:8080/users
Accept: application/json

### GET user by ID
GET http://localhost:8080/users/1
Accept: application/json

### CREATE new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstname": "Bruce",
  "lastname": "Willis",
  "username": "bruce.w",
  "email": "bruce@example.com",
  "password": "secret789"
}

### UPDATE user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "firstname": "Dwayne",
  "lastname": "Johnson",
  "username": "dwayne.johnson.updated",
  "email": "dwayne.new@example.com",
  "password": "password123"
}

### DELETE user
DELETE http://localhost:8080/users/2