CREATE TABLE user_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(100),
    lastname VARCHAR(100),
    username VARCHAR(100),
    email VARCHAR(100),
    password VARCHAR(100)
);

INSERT INTO user_entity (firstname, lastname, username, email, password)
VALUES
    ('Jason', 'Statham', 'jason.statham', 'jason.statham@example.com', 'password456');

INSERT INTO user_entity (firstname, lastname, username, email, password)
VALUES
    ('Jason', 'Statham', 'jason.statham', 'jason.statham@example.com', 'password456');

SELECT * FROM user_entity;
